# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'screen_record.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt, QDateTime, QTimer
from PyQt5.QtWidgets import QFileDialog

from src.logcat.log import z_logger

record_file_path = "/sdcard/easy_screenrecord.mp4"
resolution_default = "1920x1080"


class Record_Dialog(object):
    def __init__(self):
        self.record_file_save_path = None
        self.recordThread = None
        self.record_remaining_seconds = None
        self.h_layout_1 = None
        self.dialog_root_vlayout = None
        self.timer = None
        self.time_limit_value = 90
        self.bit_rate_bytes = 8000000  # 8Mbps

    def setupUi(self, Dialog, window):
        self.mainWindow = window
        Dialog.setObjectName("Record_Dialog")
        Dialog.setWindowFlags(Qt.WindowCloseButtonHint)
        Dialog.resize(190, 187)
        self.dialog_root_vlayout = QtWidgets.QVBoxLayout(Dialog)
        self.dialog_root_vlayout.setObjectName("verticalLayout_5")
        self.h_layout_1 = QtWidgets.QHBoxLayout()
        self.h_layout_1.setObjectName("h_layout_1")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_custom_resolution = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_custom_resolution.setObjectName("is_custom_resolution")
        self.checkBox_custom_resolution.toggled.connect(
            lambda: self.on_check_box_toggled(self.checkBox_custom_resolution))

        self.verticalLayout.addWidget(self.checkBox_custom_resolution)
        self.display_resolution_edit = QtWidgets.QLineEdit(self.groupBox)
        self.display_resolution_edit.setEnabled(False)
        self.display_resolution_edit.setObjectName("resolution_value")
        self.verticalLayout.addWidget(self.display_resolution_edit)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.h_layout_1.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bitrate_check_box = QtWidgets.QCheckBox(self.groupBox_3)
        self.bitrate_check_box.setObjectName("bitrate_box")
        self.bitrate_check_box.setChecked(False)
        self.bitrate_check_box.setToolTip("“8000000”相当于“8M”。默认20Mbps。\n值越小视频画质越差。")
        self.bitrate_check_box.toggled.connect(
            lambda: self.on_check_box_toggled(self.bitrate_check_box))
        self.verticalLayout_4.addWidget(self.bitrate_check_box)
        self.bitrates = QtWidgets.QLineEdit(self.groupBox_3)
        self.bitrates.setObjectName("bitrates")
        self.bitrates.setEnabled(False)
        self.verticalLayout_4.addWidget(self.bitrates)
        self.h_layout_1.addWidget(self.groupBox_3)
        self.h_layout_1.setStretch(0, 2)
        self.h_layout_1.setStretch(1, 1)
        self.dialog_root_vlayout.addLayout(self.h_layout_1)
        self.groupBox_limit = QtWidgets.QGroupBox(Dialog)
        self.groupBox_limit.setObjectName("groupBox_limit")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_limit)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.recode_time_progress = QtWidgets.QLabel(self.groupBox_limit)
        self.recode_time_progress.setObjectName("recode_time_progress")
        self.verticalLayout_3.addWidget(self.recode_time_progress)
        self.limit_time_slider = QtWidgets.QSlider(self.groupBox_limit)
        self.limit_time_slider.setMinimum(5)
        self.limit_time_slider.setMaximum(180)
        self.limit_time_slider.setSingleStep(5)
        self.limit_time_slider.setPageStep(5)
        self.limit_time_slider.setProperty("value", self.time_limit_value)
        self.limit_time_slider.setOrientation(QtCore.Qt.Horizontal)
        self.limit_time_slider.setObjectName("limit_time_slider")
        self.limit_time_slider.valueChanged.connect(lambda: self.on_limit_time_changed(self.limit_time_slider))
        self.verticalLayout_3.addWidget(self.limit_time_slider)
        self.dialog_root_vlayout.addWidget(self.groupBox_limit)

        self.groupBox__rotate = QtWidgets.QGroupBox(Dialog)
        self.groupBox__rotate.setObjectName("groupBox__rotate")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox__rotate)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.is_rotate_box = QtWidgets.QCheckBox(self.groupBox__rotate)
        self.is_rotate_box.setObjectName("is_rotate_box")
        self.is_rotate_box.toggled.connect(lambda: self.on_check_box_toggled(self.is_rotate_box))
        self.verticalLayout_2.addWidget(self.is_rotate_box)
        self.dialog_root_vlayout.addWidget(self.groupBox__rotate)
        self.btns_layout = QtWidgets.QHBoxLayout()
        self.btns_layout.setObjectName("btns_layout")
        self.btn_start = QtWidgets.QPushButton(Dialog)
        self.btn_start.setObjectName("btn_start")
        self.btn_start.clicked.connect(self.on_record_start_btn_clicked)
        self.btns_layout.addWidget(self.btn_start)
        self.btn_abort = QtWidgets.QPushButton(Dialog)
        self.btn_abort.setEnabled(False)
        self.btn_abort.setObjectName("btn_abort")
        self.btn_abort.clicked.connect(self.on_record_abort_btn_clicked)
        self.btns_layout.addWidget(self.btn_abort)
        self.btn_pull_record_file = QtWidgets.QPushButton(Dialog)
        self.btn_pull_record_file.setObjectName("btn_pull_record_file")
        self.btn_pull_record_file.clicked.connect(self.on_record_pull_btn_clicked)

        self.btns_layout.addWidget(self.btn_pull_record_file)
        self.dialog_root_vlayout.addLayout(self.btns_layout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "视频录制"))
        self.groupBox.setTitle(_translate("Dialog", "分辨率"))
        self.checkBox_custom_resolution.setText(_translate("Dialog", "自定义"))
        self.display_resolution_edit.setText(_translate("Dialog", "1920x1080"))
        self.groupBox_3.setTitle(_translate("Dialog", "比特率"))

        self.bitrate_check_box.setText(_translate("Dialog", "自定义（字节）"))
        self.bitrates.setText(_translate("Dialog", str(self.bit_rate_bytes)))
        self.groupBox_limit.setTitle(_translate("Dialog", "时间限制"))
        self.recode_time_progress.setText(_translate("Dialog", "录制时间(秒):90"))
        self.groupBox__rotate.setTitle(_translate("Dialog", "旋转"))
        self.is_rotate_box.setText(_translate("Dialog", "输出视频旋转90度(实验性)"))
        self.btn_start.setText(_translate("Dialog", "开始"))
        self.btn_abort.setText(_translate("Dialog", "终止"))
        self.btn_pull_record_file.setText(_translate("Dialog", "拉取"))

    def on_check_box_toggled(self, check_box):
        if self.checkBox_custom_resolution == check_box:
            if not check_box.isChecked():
                self.display_resolution_edit.setText(resolution_default)
            self.display_resolution_edit.setEnabled(check_box.isChecked())
        if self.bitrate_check_box == check_box:
            if not check_box.isChecked():
                self.bitrates.setText(str(self.bit_rate_bytes))
            self.bitrates.setEnabled(check_box.isChecked())

    def on_limit_time_changed(self, value):
        slider_value = value.value()
        self.time_limit_value = slider_value
        self.recode_time_progress.setText("录制时间(秒):%s" % self.time_limit_value)

    def on_record_pull_btn_clicked(self):
        """
        拉取录屏文件行为
        :return:
        """
        if not self.record_file_save_path:
            _name = QDateTime.currentDateTime().toString("yyyyMMdd_hhmmss")
            self.record_file_save_path = f"{os.getcwd()}{os.path.sep}{_name}.mp4"
        self.mainWindow.adbTools.exec_adb_cmd(f"adb -s {self.mainWindow.current_device_addr} pull {record_file_path} {self.record_file_save_path}")

    def on_record_abort_btn_clicked(self):
        """
        终止录屏行为
        :return:
        """
        self.mainWindow.adbTools.stop_screen_record()
        self.timer.stop()
        self.btn_start.setText('开始')
        self.btn_start.setEnabled(True)
        self.btn_abort.setEnabled(False)

    def on_record_start_btn_clicked(self):
        """
        执行屏幕录制，并保存至本地
        :return:
        """
        if len(self.mainWindow.connected_device_list) == 0:
            z_logger.error("请先连接设备!!!")
            return
        chooseDialog = QFileDialog
        default_file_name = QDateTime.currentDateTime().toString("yyyyMMdd_hhmmss")
        self.record_file_save_path = chooseDialog.getSaveFileName(
            self.mainWindow, "保存视频", f"screenshot_{default_file_name}.mp4",
            "Video Files (*.mp4)")[0]
        if self.record_file_save_path:
            self.btn_start.setEnabled(False)
            self.btn_abort.setEnabled(True)
            self.timer = QTimer(self.mainWindow)
            self.timer.timeout.connect(self.update_label)
            self.timer.start(1000)
            self.record_remaining_seconds = int(self.time_limit_value)
            self.mainWindow.adbTools.start_screen_record(self.mainWindow.current_device_addr, self.get_record_cmd(),
                                                         record_file_path, self.record_file_save_path)
        else:
            z_logger.info("Cancle screen record.")

    def get_record_cmd(self):
        cmd = f"screenrecord --verbose"
        cmd += f" --time-limit {self.time_limit_value}"
        if self.bitrate_check_box.isChecked():
            self.bit_rate_bytes = self.bitrates.text()
            cmd += f" --bit-rate {self.bit_rate_bytes}"
        if self.display_resolution_edit.isEnabled():
            cmd += f" --size {self.display_resolution_edit.text()}"
        if self.is_rotate_box.isChecked():
            cmd += " --rotate"
        cmd += f" {record_file_path}"
        return cmd

    def update_label(self):
        self.record_remaining_seconds = self.record_remaining_seconds - 1
        if self.record_remaining_seconds > 0:
            self.btn_start.setText(str(self.record_remaining_seconds) + "s")
        else:
            self.timer.stop()
            self.btn_start.setText('开始')
            self.btn_start.setEnabled(True)
            self.btn_abort.setEnabled(False)
