# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'device_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_device_info_area(object):
    def setupUi(self, device_info_area):
        device_info_area.setObjectName("device_info_area")
        device_info_area.resize(191, 378)
        device_info_area.setStyleSheet("background-color:rgb(239, 245, 249);")
        self.verticalLayoutWidget = QtWidgets.QWidget(device_info_area)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 171, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.deviceInfoLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.deviceInfoLayout.setContentsMargins(0, 0, 6, 0)
        self.deviceInfoLayout.setObjectName("deviceInfoLayout")
        self.device_alias = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.device_alias.setStyleSheet("background-color:rgb(7=239, 245, 249);font-size:16px; font-weight: bold;")
        self.device_alias.setTextFormat(QtCore.Qt.PlainText)
        self.device_alias.setAlignment(QtCore.Qt.AlignCenter)
        self.device_alias.setWordWrap(True)
        self.device_alias.setObjectName("device_alias")
        self.deviceInfoLayout.addWidget(self.device_alias)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.device_ip = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.device_ip.setObjectName("device_ip")
        self.horizontalLayout.addWidget(self.device_ip)
        self.device_state = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.device_state.setTextFormat(QtCore.Qt.PlainText)
        self.device_state.setScaledContents(False)
        self.device_state.setObjectName("device_state")
        self.horizontalLayout.addWidget(self.device_state)
        self.deviceInfoLayout.addLayout(self.horizontalLayout)
        self.device_list = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.device_list.setObjectName("device_list")
        self.deviceInfoLayout.addWidget(self.device_list)
        self.function_fast = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.function_fast.setStyleSheet("background-color:rgb(7=239, 245, 249);font-size:12px; font-weight: bold;")
        self.function_fast.setObjectName("function_fast")
        self.deviceInfoLayout.addWidget(self.function_fast)
        self.file_manager = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.file_manager.setStyleSheet("background-color:rgb(7=239, 245, 249);font-size:12px; font-weight: bold;")
        self.file_manager.setObjectName("file_manager")
        self.deviceInfoLayout.addWidget(self.file_manager)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.deviceInfoLayout.addItem(spacerItem)

        self.retranslateUi(device_info_area)
        QtCore.QMetaObject.connectSlotsByName(device_info_area)

    def retranslateUi(self, device_info_area):
        _translate = QtCore.QCoreApplication.translate
        device_info_area.setWindowTitle(_translate("device_info_area", "Form"))
        self.device_alias.setText(_translate("device_info_area", "ZTE-B860A-Android9"))
        self.device_ip.setText(_translate("device_info_area", "IP：172.31.10.165"))
        self.device_state.setText(_translate("device_info_area", "已连接"))
        self.function_fast.setText(_translate("device_info_area", "常用快捷功能"))
        self.file_manager.setText(_translate("device_info_area", "文件管理"))
