# -*- coding: utf-8 -*-
import sys

import win32gui
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QWindow
from PyQt5.QtWidgets import QMainWindow, QSizePolicy, QWidget, QApplication, QVBoxLayout, QFrame


# Form implementation generated from reading ui file 'windowWrapper.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


class Ui_Form(QWidget):
    def __init__(self):
        super().__init__()
        container = None
        self.myhwnd = None
        self.scrcpy_hwnd = -1
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(860, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")

        self.showBtn = QtWidgets.QPushButton(Form)
        self.showBtn.clicked.connect(self.findScrcpy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showBtn.sizePolicy().hasHeightForWidth())
        self.showBtn.setSizePolicy(sizePolicy)
        self.showBtn.setObjectName("showBtn")
        self.verticalLayout.addWidget(self.showBtn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.myhwnd = int(self.winId())

    def findScrcpy(self):
        # win32gui.EnumWindows(self.__enumWindows, None)
        self.scrcpy_hwnd = win32gui.FindWindow(None, "MiTV-AZFP0")
        if self.scrcpy_hwnd != -1:
            # 找到scrcpy的窗口
            window: QWindow = QWindow.fromWinId(self.scrcpy_hwnd)
            window.setFlags(Qt.WindowType.CustomizeWindowHint)
            # 创建一个QWidget并将QWindow添加到其中
            widget = QWidget()

            container: QWidget = QWidget.createWindowContainer(window,widget)
            layout = QVBoxLayout(widget)
            layout.addWidget(container)

            # container.setWindowFlags()
            # 保留原始窗口的边框和标题栏, 直接使用 QWindow 对象，并将其嵌入到一个 QWidget
            # embedded_window = EmbeddedWindow(_hwnd)
            sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
            sizePolicy.setHeightForWidth(container.sizePolicy().hasHeightForWidth())
            container.setSizePolicy(sizePolicy)
            container.setFixedHeight(720)
            container.setFixedWidth(1280)

            self.verticalLayout.addWidget(widget)
            self.verticalLayout.setStretch(1, 2)
        else:
            print('未找到scrcpy设备！！！')

    def __enumWindows(self, hwnd, what):
        """遍历回调函数"""
        if hwnd == self.myhwnd:
            return  # 过滤自己

        if win32gui.IsWindow(hwnd) and win32gui.IsWindowVisible(hwnd) and win32gui.IsWindowEnabled(hwnd):
            phwnd = win32gui.GetParent(hwnd)
            title = win32gui.GetWindowText(hwnd)
            name = win32gui.GetClassName(hwnd)
            _info = f'{hwnd:<10}|{phwnd:<10}|标题：{title:<10}|类名：{name:<10}'
            if name == "SDL_app":
                print(f"Scrcpy的信息为:{_info}")
                self.scrcpy_hwnd = hwnd


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.showBtn.setText(_translate("Form", "连接设备屏幕"))


# class NativeWidget(QWidget):
#     def __init__(self, win_id):
#         super().__init__()
#         self.window = QWindow.fromWinId(win_id)
#         self.createWinId()
#
#     def createWinId(self):
#         self.setAttribute(Qt.WA_NativeWindow)
#         self.window.setTransientParent(self.winId())
#
#     def nativeEvent(self, eventType, message):
#         if eventType == "windows_generic_MSG":
#             # 处理 Windows 原生窗口事件
#             # 可以在这里自定义窗口边框和按钮的行为
#             pass
#         return super().nativeEvent(eventType, message)


import sys
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5.QtCore import QEvent, Qt
from PyQt5.QtGui import QWindow

class NativeWidget(QWidget):
    def __init__(self, win_id):
        super().__init__()
        self.window = QWindow.fromWinId(win_id)
        self.createWinId()

    def createWinId(self):
        self.setAttribute(Qt.WA_NativeWindow)
        self.window.setTransientParent(self.winId())

    def nativeEvent(self, eventType, message):
        if eventType == "windows_generic_MSG":
            # 处理 Windows 原生窗口事件
            # 可以在这里自定义窗口边框和按钮的行为
            pass
        return super().nativeEvent(eventType, message)


# if __name__ == '__main__':
#     app = QApplication(sys.argv)
#     win_id = 1053714  # 替换为真实的窗口句柄
#     widget = NativeWidget(win_id)
#     widget.show()
#     sys.exit(app.exec_())

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = Ui_Form()
    window.show()
    sys.exit(app.exec_())