# -*- coding: utf-8 -*-
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QToolBar, QApplication

from utils.UITools import IconTool
from utils.UiWidgts import AppPushButton


# Form implementation generated from reading ui file 'toolbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


class Ui_ToolBar(QToolBar):
    def __init__(self, context):
        super().__init__()
        self.mainWindow = context
        self.setupUi()

    """
    App快捷工具栏(菜单栏下面)
    """
    def setupUi(self):
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.setLayout(self.horizontalLayout)
        self.setContentsMargins(5,0, 0, 0)

        self.pb_adddevice = AppPushButton("", self.mainWindow.show_new_device_dialog)
        iconAdd = IconTool.buildQIcon("add_new.png", "icons")
        self.pb_adddevice.setIcon(iconAdd)
        self.pb_adddevice.setIconSize(QtCore.QSize(18, 18))
        self.pb_adddevice.setObjectName("add_devices")
        self.addWidget(self.pb_adddevice)

        iconRefresh = IconTool.buildQIcon("refresh.png", "icons")
        self.pb_refresh = AppPushButton("", self.mainWindow.check_device_status)
        self.pb_refresh.setIcon(iconRefresh)
        self.pb_refresh.setIconSize(QtCore.QSize(18, 18))
        self.pb_refresh.setObjectName("refresh_devices")
        self.addWidget(self.pb_refresh)

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.pb_adddevice.setText(_translate("add_devices", "添加设备"))
        self.pb_refresh.setToolTip(_translate("refresh_devices", "刷新设备列表"))
        self.pb_refresh.setText(_translate("refresh_devices", "刷新设备"))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    mainWin = Ui_ToolBar(None)
    mainWin.show()
    sys.exit(app.exec_())