# -*- coding: utf-8 -*-
import os
import subprocess
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import pyqtSlot, QProcess
from PyQt5.QtWidgets import QToolBar, QApplication

from src.logcat.log import z_logger
from utils.ADBTools import ActionCmdParams
from utils.UITools import IconTool
from utils.UiWidgts import AppPushButton


# Form implementation generated from reading ui file 'toolbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


class Ui_ToolBar(QToolBar):
    def __init__(self, context):
        super().__init__()
        self.mainWindow = context
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.btn_adddevice = AppPushButton("", self.mainWindow.show_new_device_dialog)
        self.btn_openshell = AppPushButton("Open Shell", self.openShell)
        self.btn_root = AppPushButton("")
        self.btn_root.clicked.connect(lambda: self.adb_cmd_clicked("root"))

        self.btn_unroot = AppPushButton("")
        self.btn_unroot.clicked.connect(lambda: self.adb_cmd_clicked("unroot"))

        self.setupUi()

    """
    App快捷工具栏(菜单栏下面)
    """
    def setupUi(self):
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.setLayout(self.horizontalLayout)

        iconAdd = IconTool.buildQIcon("add_new_32x32.png", "icons")
        self.btn_adddevice.setIcon(iconAdd)
        self.btn_adddevice.setIconSize(QtCore.QSize(22, 22))
        self.btn_adddevice.setObjectName("add_devices")
        self.btn_adddevice.setMouseTracking(True)  # 确保鼠标悬停和点击效果仍然有效
        self.addWidget(self.btn_adddevice)

        iconOpenShell = IconTool.buildQIcon("open_shell_32x32.png", "icons")
        self.btn_openshell.setIcon(iconOpenShell)
        self.btn_openshell.setIconSize(QtCore.QSize(28, 24))
        self.btn_openshell.setObjectName("open_shell")
        self.addWidget(self.btn_openshell)

        iconRoot = IconTool.buildQIcon("root_32x32.png", "icons")
        self.btn_root.setIcon(iconRoot)
        self.btn_root.setIconSize(QtCore.QSize(22, 22))
        self.btn_root.setObjectName("root")
        self.addWidget(self.btn_root)

        iconunRoot = IconTool.buildQIcon("unroot_32x32.png", "icons")
        self.btn_unroot.setIcon(iconunRoot)
        self.btn_unroot.setIconSize(QtCore.QSize(22, 22))
        self.btn_unroot.setObjectName("unroot")
        self.addWidget(self.btn_unroot)

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.btn_adddevice.setText(_translate("add_devices", "添加设备"))
        self.btn_root.setText(_translate("root_adb", "ADB Root"))
        self.btn_unroot.setText(_translate("unroot_adb", "ADB Unroot"))

    @pyqtSlot()
    def adb_cmd_clicked(self, action, hasTargetApp=False):
        _params = ActionCmdParams()
        _params.isShellMode = False
        _params.needDstPkg = hasTargetApp
        _params.cmd = action
        self.mainWindow.runAdbCMD(_params)

    @pyqtSlot()
    def openShell(self):
        if not self.mainWindow.is_current_device_connect():
            z_logger.error("请先连接设备！！")
            return
        current_device = self.mainWindow.current_device_addr
        local_app_data = os.getenv('LOCALAPPDATA')
        wt_path = f"{local_app_data}\Microsoft\WindowsApps\wt.exe"
        if os.path.exists(wt_path):
            cmd = f'start {wt_path} adb -s {current_device} shell'
        else:
            shell_path = "C:\Windows\System32\cmd.exe"
            cmd = f'start {shell_path} /k adb -s {current_device} shell'
        os.system(cmd)



if __name__ == "__main__":
    app = QApplication(sys.argv)
    mainWin = Ui_ToolBar(None)
    mainWin.show()
    sys.exit(app.exec_())
